
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "woolf/internal/openrouter"


)

var tests = []testing.InternalTest{

	{"TestStreamChatParsesSSE", _test.TestStreamChatParsesSSE},

	{"TestStreamChatMapsHTTPError", _test.TestStreamChatMapsHTTPError},

	{"TestStreamChatRequiresAPIKey", _test.TestStreamChatRequiresAPIKey},

	{"TestStreamChatMapsStatusCodes", _test.TestStreamChatMapsStatusCodes},

	{"TestStreamChatRetriesRateLimitWithRetryAfter", _test.TestStreamChatRetriesRateLimitWithRetryAfter},

	{"TestStreamChatDefaultRetriesServerErrors", _test.TestStreamChatDefaultRetriesServerErrors},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "woolf"
	testdeps.ImportPath = "woolf/internal/openrouter"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

