
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "woolf/internal/agents"


)

var tests = []testing.InternalTest{

	{"TestBuiltinRegistryResolvesPresets", _test.TestBuiltinRegistryResolvesPresets},

	{"TestLoadUserRoleValidation", _test.TestLoadUserRoleValidation},

	{"TestRoleValidationRejectsBadStance", _test.TestRoleValidationRejectsBadStance},

	{"TestRoleValidationRejectsUnsafeNames", _test.TestRoleValidationRejectsUnsafeNames},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "woolf"
	testdeps.ImportPath = "woolf/internal/agents"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

