
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "woolf/internal/cli"


)

var tests = []testing.InternalTest{

	{"TestAgentsListAndShowRoles", _test.TestAgentsListAndShowRoles},

	{"TestAgentsAddAndDeleteCustomRole", _test.TestAgentsAddAndDeleteCustomRole},

	{"TestAgentsDeleteRejectsUnsafeName", _test.TestAgentsDeleteRejectsUnsafeName},

	{"TestNewRootCommandRegistersExpectedSubcommands", _test.TestNewRootCommandRegistersExpectedSubcommands},

	{"TestStartCommandRunsPipelineWithFakeClient", _test.TestStartCommandRunsPipelineWithFakeClient},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "woolf"
	testdeps.ImportPath = "woolf/internal/cli"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

