
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "woolf/internal/session"


)

var tests = []testing.InternalTest{

	{"TestCreateSaveLoadAndList", _test.TestCreateSaveLoadAndList},

	{"TestLoadResolvesPrefixAndListIndex", _test.TestLoadResolvesPrefixAndListIndex},

	{"TestLoadAmbiguousPrefix", _test.TestLoadAmbiguousPrefix},

	{"TestResumePersistsActiveStatus", _test.TestResumePersistsActiveStatus},

	{"TestForkCopiesSessionAndCanReplaceSource", _test.TestForkCopiesSessionAndCanReplaceSource},

	{"TestDeleteRemovesSession", _test.TestDeleteRemovesSession},

	{"TestLoadCorruptJSON", _test.TestLoadCorruptJSON},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "woolf"
	testdeps.ImportPath = "woolf/internal/session"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

