
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "woolf/internal/orchestrator"


)

var tests = []testing.InternalTest{

	{"TestContextBuilderIncludesDraftInterventionsAndPriorResponses", _test.TestContextBuilderIncludesDraftInterventionsAndPriorResponses},

	{"TestContextBuilderUsesSourcePreviewWhenContentIsEmpty", _test.TestContextBuilderUsesSourcePreviewWhenContentIsEmpty},

	{"TestPipelineRunsAgentsAndPersistsSession", _test.TestPipelineRunsAgentsAndPersistsSession},

	{"TestPipelineContextCancelPausesSession", _test.TestPipelineContextCancelPausesSession},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "woolf"
	testdeps.ImportPath = "woolf/internal/orchestrator"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

