
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "woolf/internal/config"


)

var tests = []testing.InternalTest{

	{"TestLoadAppliesEnvironmentOverrides", _test.TestLoadAppliesEnvironmentOverrides},

	{"TestMaskSecret", _test.TestMaskSecret},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "woolf"
	testdeps.ImportPath = "woolf/internal/config"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

